// Package advice_kit_api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package advice_kit_api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for DescribingEndpointReferenceMethod.
const (
	GET DescribingEndpointReferenceMethod = "GET"
)

// Defines values for ValidationType.
const (
	EXPERIMENT ValidationType = "EXPERIMENT"
	TEXT       ValidationType = "TEXT"
)

// AdviceDefinition Provides details about a advice
type AdviceDefinition struct {
	// AssessmentQueryApplicable A Assessment Target Base Query that is used identifies targets that could have this advice.
	AssessmentQueryApplicable string `json:"assessmentQueryApplicable"`

	// Icon A svg of an icon that represents the advice.
	Icon string `json:"icon"`

	// Id A technical ID that is used to uniquely identify this type of advice. You will typically want to use something like `org.example.extension.my-fancy-advice`.
	Id string `json:"id"`

	// Label A human-readable label for the advice.
	Label string `json:"label"`

	// Status Provides details about a advice
	Status AdviceDefinitionStatus `json:"status"`

	// Tags A list of tags that describe the advice.
	Tags *[]string `json:"tags,omitempty"`

	// Version The version of the advice. This is used to identify the version of the advice and is used for compatibility checks.
	Version string `json:"version"`
}

// AdviceDefinitionStatus Provides details about a advice
type AdviceDefinitionStatus struct {
	// ActionNeeded Provides details about a advice lifecycle status actions needed
	ActionNeeded AdviceDefinitionStatusActionNeeded `json:"actionNeeded"`

	// Implemented Provides details about a advice lifecycle status implemented
	Implemented AdviceDefinitionStatusImplemented `json:"implemented"`

	// ValidationNeeded Provides details about a advice lifecycle status validation needed
	ValidationNeeded AdviceDefinitionStatusValidationNeeded `json:"validationNeeded"`
}

// AdviceDefinitionStatusActionNeeded Provides details about a advice lifecycle status actions needed
type AdviceDefinitionStatusActionNeeded struct {
	// AssessmentQuery A Assessment Target Query Addon that is used to identify targets with this advice in the target list of the assessmentQueryApplicable
	AssessmentQuery string `json:"assessmentQuery"`

	// Description Provides details description about a advice lifecycle status actions needed
	Description AdviceDefinitionStatusActionNeededDescription `json:"description"`
}

// AdviceDefinitionStatusActionNeededDescription Provides details description about a advice lifecycle status actions needed
type AdviceDefinitionStatusActionNeededDescription struct {
	// Instruction A human-readable instructions of the action needed in mark down format. (you can use placeholder like ${target.k8s.pod.name})
	Instruction string `json:"instruction"`

	// Motivation A human-readable motivation of the action needed in mark down format. (you can use placeholder like ${target.k8s.pod.name})
	Motivation string `json:"motivation"`

	// Summary A human-readable summary of the action needed in mark down format. (you can use placeholder like ${target.k8s.pod.name})
	Summary string `json:"summary"`
}

// AdviceDefinitionStatusImplemented Provides details about a advice lifecycle status implemented
type AdviceDefinitionStatusImplemented struct {
	// Description Provides details description about a advice lifecycle status implemented
	Description AdviceDefinitionStatusImplementedDescription `json:"description"`
}

// AdviceDefinitionStatusImplementedDescription Provides details description about a advice lifecycle status implemented
type AdviceDefinitionStatusImplementedDescription struct {
	// Summary A human-readable summary of the implemented in mark down format. (you can use placeholder like ${target.k8s.pod.name})
	Summary string `json:"summary"`
}

// AdviceDefinitionStatusValidationNeeded Provides details about a advice lifecycle status validation needed
type AdviceDefinitionStatusValidationNeeded struct {
	// Description Provides details description about a advice lifecycle status validation needed
	Description AdviceDefinitionStatusValidationNeededDescription `json:"description"`

	// Validation A list of validations that are available for this advice.
	Validation *[]Validation `json:"validation,omitempty"`
}

// AdviceDefinitionStatusValidationNeededDescription Provides details description about a advice lifecycle status validation needed
type AdviceDefinitionStatusValidationNeededDescription struct {
	// Summary A human-readable summary of the validation needed in mark down format. (you can use placeholder like ${target.k8s.pod.name})
	Summary string `json:"summary"`
}

// AdviceKitError RFC 7807 Problem Details for HTTP APIs compliant response body for error scenarios
type AdviceKitError struct {
	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Title A short, human-readable summary of the problem type.
	Title string `json:"title"`

	// Type A URI reference that identifies the problem type.
	Type *string `json:"type,omitempty"`
}

// AdviceList Lists all advice that the platform/agent could consume.
type AdviceList struct {
	Advice []DescribingEndpointReference `json:"advice"`
}

// DescribingEndpointReference HTTP endpoint which the Steadybit platform/agent could communicate with.
type DescribingEndpointReference struct {
	// Method HTTP method to use when calling the HTTP endpoint.
	Method DescribingEndpointReferenceMethod `json:"method"`

	// Path Absolute path of the HTTP endpoint.
	Path string `json:"path"`
}

// DescribingEndpointReferenceMethod HTTP method to use when calling the HTTP endpoint.
type DescribingEndpointReferenceMethod string

// Experiment Provides a experiment json exported from the ui
type Experiment = interface{}

// Validation Provides a either a template about a advice experiment or a textual validation like a checklist item
type Validation struct {
	// Description A human-readable description for the validation or for the experiment template.
	Description string `json:"description"`

	// Experiment Provides a experiment json exported from the ui
	Experiment *Experiment `json:"experiment,omitempty"`

	// Id A technical ID that is used to uniquely identify this validation. You will typically want to use something like `org.example.extension.my-fancy-advice-validation.1`.
	Id string `json:"id"`

	// Name A human-readable name for the validation.
	Name string `json:"name"`

	// Type The type of the validation. Either `EXPERIMENT` or `TEXT`.
	Type ValidationType `json:"type"`
}

// ValidationType The type of the validation. Either `EXPERIMENT` or `TEXT`.
type ValidationType string

// AdviceDefinitionResponse defines model for AdviceDefinitionResponse.
type AdviceDefinitionResponse struct {
	union json.RawMessage
}

// AdviceListResponse defines model for AdviceListResponse.
type AdviceListResponse struct {
	union json.RawMessage
}

// AsAdviceDefinition returns the union data inside the AdviceDefinitionResponse as a AdviceDefinition
func (t AdviceDefinitionResponse) AsAdviceDefinition() (AdviceDefinition, error) {
	var body AdviceDefinition
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAdviceDefinition overwrites any union data inside the AdviceDefinitionResponse as the provided AdviceDefinition
func (t *AdviceDefinitionResponse) FromAdviceDefinition(v AdviceDefinition) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAdviceDefinition performs a merge with any union data inside the AdviceDefinitionResponse, using the provided AdviceDefinition
func (t *AdviceDefinitionResponse) MergeAdviceDefinition(v AdviceDefinition) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsAdviceKitError returns the union data inside the AdviceDefinitionResponse as a AdviceKitError
func (t AdviceDefinitionResponse) AsAdviceKitError() (AdviceKitError, error) {
	var body AdviceKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAdviceKitError overwrites any union data inside the AdviceDefinitionResponse as the provided AdviceKitError
func (t *AdviceDefinitionResponse) FromAdviceKitError(v AdviceKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAdviceKitError performs a merge with any union data inside the AdviceDefinitionResponse, using the provided AdviceKitError
func (t *AdviceDefinitionResponse) MergeAdviceKitError(v AdviceKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t AdviceDefinitionResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AdviceDefinitionResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsAdviceList returns the union data inside the AdviceListResponse as a AdviceList
func (t AdviceListResponse) AsAdviceList() (AdviceList, error) {
	var body AdviceList
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAdviceList overwrites any union data inside the AdviceListResponse as the provided AdviceList
func (t *AdviceListResponse) FromAdviceList(v AdviceList) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAdviceList performs a merge with any union data inside the AdviceListResponse, using the provided AdviceList
func (t *AdviceListResponse) MergeAdviceList(v AdviceList) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsAdviceKitError returns the union data inside the AdviceListResponse as a AdviceKitError
func (t AdviceListResponse) AsAdviceKitError() (AdviceKitError, error) {
	var body AdviceKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAdviceKitError overwrites any union data inside the AdviceListResponse as the provided AdviceKitError
func (t *AdviceListResponse) FromAdviceKitError(v AdviceKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAdviceKitError performs a merge with any union data inside the AdviceListResponse, using the provided AdviceKitError
func (t *AdviceListResponse) MergeAdviceKitError(v AdviceKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t AdviceListResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AdviceListResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RZX28buRH/KgM2D22xlh30IYHe1FpthTap6+iCHAIfTHFHWsZcckNybS8MffcDyV2J",
	"+0eyLMWXN2tJzvxm5jcz5PiJMJUXSqK0hoyfiEZTKGnQ/5ik95zhJS655JYreV0vujWmpEVp3Z+0KARn",
	"1O04/2aUdN8MyzCnflVW/1uS8dcn8kbjkozJn863Ks/DPnPeVUXWySEH/sPtVGulyfpmvV4nJEXDNC+8",
	"hDFp8MJSabAZQlheIFB/GlCmheLSkoRYbgWSMblstgQFsLF5ndT++C839tU94ZS8jg9q0wU3dsj+2myn",
	"P7J9ndR2DPLCfWtrvdLqnqdoIEVLuTBAF6q0QGvtJCGFVgVqywPTqDFoTI7S/r9EXU2CHxcC+6InMNls",
	"hjnVK7Twd2oQ/EmwGbXADZQGU+ApSsuXHA1Yv9OEdaZKkUJG7xFsxk2NauTcUBXOC8ZqLlcu5pwN2TcB",
	"c78CtQQqwe0IYjUWGo0LUeTpYanpkEyLLJOcUQGzy7YhVkEp+fcSRdUYVQXoTrQHEpTBr6qEBy6EW3Ci",
	"RAUPVFovwSAYlaPNuFyB4HcIt0qvRvhI80LgCB8tSsOVHOXV2ZJKVp0FqbeDNgi6QDFkRlbmVJ5ppKmL",
	"IPh9HfoNCjSW2tLT4SWV4lM4tU6IpSszhMdTXS3BrQe3bupAGxG3mHsJPWj1B6o1rUhCQixmYbvVJa4T",
	"co/aDObCPEOoFz2KrUqYuwhGMY5Cu+MMUJluTjifOg9RyxdccFsBy5DdmQHvrhOi8XvJNaZk/NXxb4u4",
	"CWVN9mRPNm6CdNOrGJeR0Rv1avENmd3Wzl7YTq8czB38iJhiehx1JrEEl5suGZzxxwqcRQIcMajgKT0V",
	"5eeulG5IW44Y0No27AfFb9Lx/otiCYIvkVVMIARWQbDBgGwg7+0Sh/WG0BYmadpU6cF8q7vDA7dZ3BKA",
	"S598YX1bSVw+7kmSXv1owTyVpHGkeizouKitOo66FwgbchwR8Mu2Uc/EPlo+lQdcGqtLNqy413+i3WYT",
	"vGB9kO+CnFN9B6l6kK6o5tSO4M+VKoFR6dtmISjDTIkUdWicb54CJUZ3782oUOlI0hzXfxmKfa4sv6cH",
	"gt1u/hlQTZnndDixOjjrnX88yA7fG8QtNycthuwi/XEVb9buDicWvLgkd1l+cs2IoO4rGTsKRJABsxbC",
	"lzvp9YrEPt8dTeRI6M+g8V7/H0fYzwPXjxNZu71b7KrQJ3O3i7pF4Ph2s+/Cv91V3/upRqD3lAsf+vAk",
	"aT3/Ni+AfYi32A56GhyWbluhL+7J+3z1Y1Pu+cAfnXg90T85/XrxOCz7NsOYngOu//kPePf+4h1cabUQ",
	"mMNlHQBHw3/P51cwuZoZ/54T3L3Ym1EcLFRa+V3oJINhKKnmygxknZN4gO/xsRBUButMgYwvOXP3YZ8N",
	"irFSa5QMm9gUAfHwJEMaSyUbHNT8cj0DjUsMwsLlO5rIZLhV/jKldZAGpjKZ0jZ5hmq1ZD86GRbvPxxj",
	"zzOiO7QLZkSkq+d48aSxj8N9NUCFaNLUA/HaBbUuUc7pyj2AwpSLKWnK3KPpvKbCg9rdpw+pevVglMvV",
	"tJ4aXjeuOKYM1tpvBiePQ/m1T3/PRz6fmukmPGScZd5DnyzStFpwu8tXeV5KzqhF/xTsOy1Hm6l0h8Kw",
	"2IzaHjKUwKgQXK688hYoJxplmTtf/Gs6947o8rCgNhvg4cIoUVoEt9xwuie7oNaidvt/Ox/99c2zXPS6",
	"ksa+KCxecuNyaMV8+lig5nk9/N7RZ6irNvU2+GaUdL+VdveZpVa5R19y4tA47lFZ9afRkaJ1EpXm/Wq5",
	"zVADBYu5izZ221uES4V9j7akIm5FvqvQMFbztwqXKs/ddp4pvnHDbaaikUqlN18jgI0Ng/UKW3HYl8Rt",
	"R/64KfQW/+tMoM8iBW+Hx9Gu1R/gfbdtwO0v6APzDDdT944QmAbO3U6/XE2vZx+mH+e3LqC38+mX+W2c",
	"8tsNJCFudaAADM1svZXtoU59rl9Jozzp1VMnvO4Mxpfj7n+ublxrXypnvuAM6/91bdqdJmPyYTZvEIUf",
	"6/j10hTazb3I3W+iqfOYvB1djC7cIVWgpAUnY/K30dvRRahemSFjWQrhky0t2S6c698DAAD///Z5o47D",
	"HAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
