version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: "gomod"
  directory: /go/advice_kit_api
  schedule:
    interval: "weekly"
- package-ecosystem: "gomod"
  directory: /go/advice_kit_test
  schedule:
    interval: "weekly"