openapi: 3.1.0
info:
  title: Steadybit WeakspotKit API
  version: 1.0.0
  license:
    name: MIT
    identifier: MIT
consumes:
  - application/json
produces:
  - application/json
components:
  schemas:
    WeakspotList:
      title: Weakspot List
      description: Lists all weakspots that the platform/agent could consume.
      type: object
      properties:
        weakspots:
          type: array
          items:
            $ref: '#/components/schemas/DescribingEndpointReference'
          uniqueItems: true
      required:
        - weakspots
    WeakspotDescription:
      title: Weakspot Description
      description: Provides details about a weakspot
      type: object
      properties:
        id:
          type: string
          description: "A technical ID that is used to uniquely identify this type of weakspot. You will typically want to use something like `org.example.extension.my-fancy-weakspot`."
        version:
          type: string
          description: "The version of the weakspot. This is used to identify the version of the weakspot and is used for compatibility checks."
        label:
          type: string
          description: "A human-readable label for the weakspot."
        icon:
          type: string
          description: "A svg of an icon that represents the weakspot."
        assesmentBaseQuery:
          type: string
          description: "A Assessment Target Base Query that is used identifies targets that could have this weakspot."
        assesmentQueryAddon:
          type: string
          description: "A Assessment Target Query Addon that is used to identify targets with this weakspot in the target list of the assesmentBaseQuery"
        tags:
            type: array
            items:
                type: string
            uniqueItems: true
            description: "A list of tags that describe the weakspot."
        experiments:
          type: array
          items:
            $ref: '#/components/schemas/Experiment'
          uniqueItems: true
          description: "A list of experiments that are available for this weakspot."
      required:
        - id
        - version
        - label
        - icon
        - assesmentBaseQuery
        - assesmentQueryAddon
    Experiment:
      title: Weakspot Experiment
      description: Provides a template about a weakspot experiment
      ref: any
    DescribingEndpointReference:
      title: HTTP Endpoint Reference
      description: HTTP endpoint which the Steadybit platform/agent could communicate with.
      properties:
        path:
          description: Absolute path of the HTTP endpoint.
          type: string
          pattern: ^/.*$
        method:
          description: HTTP method to use when calling the HTTP endpoint.
          type: string
          enum:
            - GET
      required:
        - path
        - method
    WeakspotKitError:
      title: Error
      description: >-
        RFC 7807 Problem Details for HTTP APIs compliant response body for error
        scenarios
      properties:
        type:
          type: string
          description: A URI reference that identifies the problem type.
        title:
          type: string
          description: 'A short, human-readable summary of the problem type.'
        detail:
          type: string
          description: >-
            A human-readable explanation specific to this occurrence of the
            problem.
        instance:
          type: string
          description: >-
            A URI reference that identifies the specific occurrence of the
            problem.
      required:
        - title
  responses:
    WeakspotListResponse:
      title: Weakspot List Response
      description: Response for the weakspot list endpoint
      content:
        application/json:
          schema:
            anyOf:
              - $ref: '#/components/schemas/WeakspotList'
              - $ref: '#/components/schemas/WeakspotKitError'
    WeakspotDescriptionResponse:
      title: Describe Weakspot Response
      description: Response for the describe weakspot endpoint
      content:
        application/json:
          schema:
            anyOf:
              - $ref: '#/components/schemas/WeakspotDescription'
              - $ref: '#/components/schemas/WeakspotKitError'
