// Package weakspot_kit_api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package weakspot_kit_api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for DescribingEndpointReferenceMethod.
const (
	GET DescribingEndpointReferenceMethod = "GET"
)

// DescribingEndpointReference HTTP endpoint which the Steadybit platform/agent could communicate with.
type DescribingEndpointReference struct {
	// Method HTTP method to use when calling the HTTP endpoint.
	Method DescribingEndpointReferenceMethod `json:"method"`

	// Path Absolute path of the HTTP endpoint.
	Path string `json:"path"`
}

// DescribingEndpointReferenceMethod HTTP method to use when calling the HTTP endpoint.
type DescribingEndpointReferenceMethod string

// Experiment Provides a template about a weakspot experiment
type Experiment = interface{}

// WeakspotDescription Provides details about a weakspot
type WeakspotDescription struct {
	// AssesmentBaseQuery A Assessment Target Base Query that is used identifies targets that could have this weakspot.
	AssesmentBaseQuery string `json:"assesmentBaseQuery"`

	// AssesmentQueryAddon A Assessment Target Query Addon that is used to identify targets with this weakspot in the target list of the assesmentBaseQuery
	AssesmentQueryAddon string `json:"assesmentQueryAddon"`

	// Experiments A list of experiments that are available for this weakspot.
	Experiments *[]Experiment `json:"experiments,omitempty"`

	// Icon A svg of an icon that represents the weakspot.
	Icon string `json:"icon"`

	// Id A technical ID that is used to uniquely identify this type of weakspot. You will typically want to use something like `org.example.extension.my-fancy-weakspot`.
	Id string `json:"id"`

	// Label A human-readable label for the weakspot.
	Label string `json:"label"`

	// Tags A list of tags that describe the weakspot.
	Tags *[]string `json:"tags,omitempty"`

	// Version The version of the weakspot. This is used to identify the version of the weakspot and is used for compatibility checks.
	Version string `json:"version"`
}

// WeakspotKitError RFC 7807 Problem Details for HTTP APIs compliant response body for error scenarios
type WeakspotKitError struct {
	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Title A short, human-readable summary of the problem type.
	Title string `json:"title"`

	// Type A URI reference that identifies the problem type.
	Type *string `json:"type,omitempty"`
}

// WeakspotList Lists all weakspots that the platform/agent could consume.
type WeakspotList struct {
	Weakspots []DescribingEndpointReference `json:"weakspots"`
}

// WeakspotDescriptionResponse defines model for WeakspotDescriptionResponse.
type WeakspotDescriptionResponse struct {
	union json.RawMessage
}

// WeakspotListResponse defines model for WeakspotListResponse.
type WeakspotListResponse struct {
	union json.RawMessage
}

// AsWeakspotDescription returns the union data inside the WeakspotDescriptionResponse as a WeakspotDescription
func (t WeakspotDescriptionResponse) AsWeakspotDescription() (WeakspotDescription, error) {
	var body WeakspotDescription
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWeakspotDescription overwrites any union data inside the WeakspotDescriptionResponse as the provided WeakspotDescription
func (t *WeakspotDescriptionResponse) FromWeakspotDescription(v WeakspotDescription) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWeakspotDescription performs a merge with any union data inside the WeakspotDescriptionResponse, using the provided WeakspotDescription
func (t *WeakspotDescriptionResponse) MergeWeakspotDescription(v WeakspotDescription) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsWeakspotKitError returns the union data inside the WeakspotDescriptionResponse as a WeakspotKitError
func (t WeakspotDescriptionResponse) AsWeakspotKitError() (WeakspotKitError, error) {
	var body WeakspotKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWeakspotKitError overwrites any union data inside the WeakspotDescriptionResponse as the provided WeakspotKitError
func (t *WeakspotDescriptionResponse) FromWeakspotKitError(v WeakspotKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWeakspotKitError performs a merge with any union data inside the WeakspotDescriptionResponse, using the provided WeakspotKitError
func (t *WeakspotDescriptionResponse) MergeWeakspotKitError(v WeakspotKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t WeakspotDescriptionResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *WeakspotDescriptionResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsWeakspotList returns the union data inside the WeakspotListResponse as a WeakspotList
func (t WeakspotListResponse) AsWeakspotList() (WeakspotList, error) {
	var body WeakspotList
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWeakspotList overwrites any union data inside the WeakspotListResponse as the provided WeakspotList
func (t *WeakspotListResponse) FromWeakspotList(v WeakspotList) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWeakspotList performs a merge with any union data inside the WeakspotListResponse, using the provided WeakspotList
func (t *WeakspotListResponse) MergeWeakspotList(v WeakspotList) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsWeakspotKitError returns the union data inside the WeakspotListResponse as a WeakspotKitError
func (t WeakspotListResponse) AsWeakspotKitError() (WeakspotKitError, error) {
	var body WeakspotKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWeakspotKitError overwrites any union data inside the WeakspotListResponse as the provided WeakspotKitError
func (t *WeakspotListResponse) FromWeakspotKitError(v WeakspotKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWeakspotKitError performs a merge with any union data inside the WeakspotListResponse, using the provided WeakspotKitError
func (t *WeakspotListResponse) MergeWeakspotKitError(v WeakspotKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t WeakspotListResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *WeakspotListResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xX328jNRD+V0bmntBe0hMPh/JWaIEKEKUEIXQKOsc7yfrOa+/Zs01Xp/zvaLw/k3V/",
	"gARvzXr2m2+++WbW/SyUKytn0VIQq8/CY6icDRh//IHyY6gcXWFQXleknb3rzvlYOUtoif+UVWW0khyx",
	"/BCc5WdBFVjKeGqbX3Zi9e6zeOVxJ1bii+WYddnGhWUimzhmL3vnR03X3jsvjpvj8ZiJfIKxEj1p2DkP",
	"VCC0x1uEQ/c+oM0rpy2JTJAmg2IlrvqgPgkMxR+zQZufdKD/QRRO81+pMYhgdEgqMQjALCYqHLOunuiW",
	"Ti9t99cdxB3u0KNVUZhTEj+s17dDKjgUWhWRy2+EMm+2mqAyknbOl0u5R0ugXG1yUK4sa8uiIhw0FQuR",
	"icq7Cj3p1rMlUuHyRxK2h0AO6oBwKNCCksZou4/JT0gxNNq6FKt34vvrtdhkgpqK5Qjktd2zCSpJxTzV",
	"5TY4UxMCH4PbpbErSYSe4/9aLr58JWbwx0x4/FRrjzlziLmyvr7N2J2I3EsOo+bHTFw/VOh12fnxlOWt",
	"d/c6xwASCEtWG0FuXU0gJ2MxAjAbdp60Tcoak1ST6ZjO8uMMciSpTZilnzVXhoCBc3wjA/5ao28S6sMl",
	"R8UwWEu/RwIOhxgPVEgCHdgAOegcLemdxgAUI0N73pqtkPcIVOgwEFqIhAkGUjHBZZ6nak2xagnFF05p",
	"keuZNQMvdvspGdA2OquNaIe3M1tCpwTxsbkhRbgHnIS1NKVHkPdSG7k1/RY5E0kTlhH0qXV1apmOnvRe",
	"Mtva6k813rQ45Gs8ZkKrtLThfs9EpQWOaEl6rDyGjjQ+3UGdp1AJVcGrxsDN1aw/LT3TTBrFGjA0UxnS",
	"wZ+uhoM2ho8YzDRwkJb6HRQcDzQvIKM/Irx3fr/AB1lWBhf4QGiDdnZRNq930qrmdY/7PlmHkVs0qVKK",
	"upT2tUeZx5bFuNn6T0KS3D9pDj5vxRm+qeeYgxfm4M+3/B59SC6PdYHQHfauH0Vfcy+S0/T4WyBtPrzD",
	"2rBjJemtNpoaUAWqj2Hx7JrWuRhZ9y3prJuJ5GCmFsgmsWKny3Sg4bYfUJ3s3OHrP9Ps7rtv4e3XF2/h",
	"1rutwRKuusXL5cbPyOXtTYiFG80m7W+DsHV5E6OQkSEotNJrF2Ybul3lL/AgPlRG2ng5glCh0jutuFVx",
	"jJxStY9fsb5LVcs4Pb42kEzeMi7h97sb8P0nsZviydIvcEz+z5J23Ukso8J5ys7LDXVZSt+cIcd9kYaP",
	"D/5NPc9An9m1LWPitu7ieHrBnTPhpwGkMcP8dGsgUkhf3WyoS5zf2AYA/vGiD8dTN82XrJUzDUYCm0fu",
	"vPNxY4yuosAYs7v+hn25c1yK0Qq7/w6GXnmxEj/frEUmrCyx+zHaSoz34MlY83hOtstKvFlcLC74NVeh",
	"lZUWK/HV4s3ior1eFkGsbG1MFDyv1WNMj38HAAD//1QQKTIFDgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
